/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 返回进程健康状态，不访问数据库或 LLM。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description 执行轻量数据库 readiness 探针。
         */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Demo Merchants
         * @description 返回受控演示商家及其权限受限 Token。
         */
        get: operations["list_demo_merchants_api_demo_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Chat
         * @description 默认返回 SSE；明确请求 JSON 时返回与 done 同构的响应。
         */
        post: operations["post_chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_exports__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/{answer_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Feedback */
        post: operations["save_feedback_api_answers__answer_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metric Definition
         * @description 返回正式指标口径。指标目录对所有商家一致，因此不按商家过滤。
         */
        get: operations["get_metric_definition_api_metrics__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisSource
         * @enum {string}
         */
        AnalysisSource: "DATABASE" | "KNOWLEDGE" | "ATTACHMENT" | "MEMORY" | "FALLBACK" | "NONE";
        /**
         * AnswerMode
         * @description 回答模式。ATTACHMENT 为 P1 预留值，B2 不产生该模式。
         * @enum {string}
         */
        AnswerMode: "METRIC" | "DETAIL" | "RULE" | "IDENTITY" | "CHAT" | "INVALID" | "ATTACHMENT";
        /**
         * ChartType
         * @description 后端允许的图表类型。
         *
         *     约束在契约侧声明后由 OpenAPI 自动传给前端，Adapter 无须自行窄化自由字符串。
         * @enum {string}
         */
        ChartType: "LINE" | "BAR" | "PIE";
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
            /** Attachment Ids */
            attachment_ids?: string[];
            /** Client Request Id */
            client_request_id: string;
        };
        /**
         * ChatResponse
         * @description §8.2 的扁平响应；按模式字段由模型级校验控制。
         */
        ChatResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Answer */
            answer: string;
            answer_mode: components["schemas"]["AnswerMode"];
            category: components["schemas"]["QuestionCategory"] | null;
            /** Thinking Steps */
            thinking_steps?: components["schemas"]["ThinkingStep"][];
            quality_status: components["schemas"]["QualityStatus"];
            /** Quality Attempts */
            quality_attempts: number;
            /** Quality Notes */
            quality_notes?: string[];
            /** Analysis Sources */
            analysis_sources: components["schemas"]["AnalysisSource"][];
            /** Degraded */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason: string | null;
            /** Suggestions */
            suggestions?: string[];
            /** Suggestion Alternates */
            suggestion_alternates?: string[][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            query_plan?: components["schemas"]["QueryPlanSummary"] | null;
            /** Metric Code */
            metric_code?: string | null;
            /** Metric Display Name */
            metric_display_name?: string | null;
            /** Metric Unit */
            metric_unit?: string | null;
            /** Metric Definition */
            metric_definition?: string | null;
            /** Metric Sql Definition */
            metric_sql_definition?: string | null;
            /** Metric Dimensions */
            metric_dimensions?: string[] | null;
            /** Metric Source Database */
            metric_source_database?: string | null;
            /** Metric Source Table */
            metric_source_table?: string | null;
            /** Metric Report Url */
            metric_report_url?: string | null;
            metric_source?: components["schemas"]["MetricDefinitionSource"] | null;
            /** Metric Generated */
            metric_generated?: boolean | null;
            /** Metric Notice */
            metric_notice?: string | null;
            /** Metric Owner */
            metric_owner?: string | null;
            metric_status?: components["schemas"]["MetricStatus"] | null;
            /** Data Rows */
            data_rows?: {
                [key: string]: unknown;
            }[] | null;
            /** Total Rows */
            total_rows?: number | null;
            /** Truncated */
            truncated?: boolean | null;
            export?: components["schemas"]["ExportInfo"] | null;
            visualization?: components["schemas"]["Visualization"] | null;
            /** Recommendations */
            recommendations?: components["schemas"]["Recommendation"][] | null;
        };
        /**
         * ConversationAnswerPayload
         * @description 会话详情中的助手回答脱敏载荷，不携带明细行和导出 URL。
         */
        ConversationAnswerPayload: {
            /**
             * Answer Id
             * Format: uuid
             */
            answer_id: string;
            answer_mode: components["schemas"]["AnswerMode"];
            /** Thinking Steps */
            thinking_steps?: components["schemas"]["ThinkingStep"][];
            quality_status: components["schemas"]["QualityStatus"];
            /** Quality Attempts */
            quality_attempts: number;
            /** Quality Notes */
            quality_notes?: string[];
            /** Degraded */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason: string | null;
            /** Is Adopted */
            is_adopted: boolean;
            reaction: components["schemas"]["FeedbackReaction"] | null;
            /** Columns */
            columns?: string[];
            /** Total Rows */
            total_rows?: number | null;
            /** Truncated */
            truncated?: boolean | null;
        };
        /** ConversationDetailResponse */
        ConversationDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            answer_payload?: components["schemas"]["ConversationAnswerPayload"] | null;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DemoMerchant */
        DemoMerchant: {
            /**
             * Merchant Id
             * Format: uuid
             */
            merchant_id: string;
            /** Display Name */
            display_name: string;
            /** Token */
            token: string;
        };
        /** DemoMerchantListResponse */
        DemoMerchantListResponse: {
            /** Merchants */
            merchants: components["schemas"]["DemoMerchant"][];
        };
        /**
         * ErrorCode
         * @description 对外错误码。
         *
         *     这是后端实际会发出的错误码的唯一出处——不要在别处直写字符串字面量。
         *     每个成员都必须同时登记在 `docs/backend-development-plan.md` §14，
         *     否则前端按码查表渲染时会漏网（见 `docs/frontend-development-plan.md` §10）。
         *
         *     后续阶段（B3 起的意图、查询、限流、附件等）按需扩充。
         * @enum {string}
         */
        ErrorCode: "AUTH_REQUIRED" | "MERCHANT_SCOPE_VIOLATION" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "INVALID_REQUEST" | "IDEMPOTENCY_KEY_REUSED" | "REQUEST_IN_PROGRESS" | "DATA_SOURCE_UNAVAILABLE" | "EXPORT_LINK_EXPIRED" | "RATE_LIMITED" | "LLM_BUDGET_EXCEEDED" | "FORBIDDEN" | "HTTP_ERROR" | "INTERNAL_ERROR";
        /**
         * ErrorResponse
         * @description 对外稳定错误契约。
         */
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[];
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** ExportInfo */
        ExportInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * FeedbackReaction
         * @enum {string}
         */
        FeedbackReaction: "LIKE" | "DISLIKE";
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Is Adopted
             * @default false
             */
            is_adopted: boolean;
            reaction?: components["schemas"]["FeedbackReaction"] | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /**
             * Answer Id
             * Format: uuid
             */
            answer_id: string;
            /** Is Adopted */
            is_adopted: boolean;
            reaction: components["schemas"]["FeedbackReaction"] | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MetricDefinitionResponse */
        MetricDefinitionResponse: {
            /** Metric Code */
            metric_code: string;
            /** Display Name */
            display_name: string;
            /** Unit */
            unit: string;
            /** Definition */
            definition: string;
            /** Sql Definition */
            sql_definition: string;
            /** Dimensions */
            dimensions: string[];
            /** Source Database */
            source_database: string;
            /** Source Table */
            source_table: string;
            /** Report Url */
            report_url: string | null;
            source: components["schemas"]["MetricDefinitionSource"];
            /** Generated */
            generated: boolean;
            /** Notice */
            notice: string | null;
            /** Owner */
            owner: string;
            status: components["schemas"]["MetricStatus"];
        };
        /**
         * MetricDefinitionSource
         * @enum {string}
         */
        MetricDefinitionSource: "METRIC_CATALOG" | "FIELD_COMMENT" | "AI_GENERATED";
        /**
         * MetricStatus
         * @enum {string}
         */
        MetricStatus: "ACTIVE" | "DEPRECATED" | "UNVERIFIED";
        /**
         * QualityStatus
         * @enum {string}
         */
        QualityStatus: "PASSED" | "DEGRADED" | "FAILED" | "NOT_RUN";
        /** QueryPlanSummary */
        QueryPlanSummary: {
            /** Summary */
            summary: string;
        };
        /**
         * QuestionCategory
         * @description 商家问题的业务分类。
         *
         *     逐字对应参考实现 `model/QuestionCategory.java`——业务域按 1:1 复刻，
         *     B3 的意图分类会直接路由到这些值，少一个就会出现无法归类的问题。
         *     枚举值是对外契约码，只能是英文；中文名见 `CATEGORY_DISPLAY_NAMES`。
         * @enum {string}
         */
        QuestionCategory: "PLATFORM_RULE" | "TRADE" | "REFUND" | "CS_TICKET" | "COMPENSATION" | "COUPON" | "GOODS" | "MERCHANT_OTHER" | "IDENTITY" | "SCM" | "UNKNOWN";
        /** ReadyResponse */
        ReadyResponse: {
            /** Status */
            status: string;
        };
        /** Recommendation */
        Recommendation: {
            /** Title */
            title: string;
            /** Evidence */
            evidence: string;
            /** Action */
            action: string;
        };
        /** ThinkingStep */
        ThinkingStep: {
            /** Label */
            label: string;
            /** Node */
            node: string;
        };
        /** Visualization */
        Visualization: {
            /** Enabled */
            enabled: boolean;
            type?: components["schemas"]["ChartType"] | null;
            /** Allowed Types */
            allowed_types?: components["schemas"]["ChartType"][];
            /** Title */
            title?: string | null;
            /** Dimension Key */
            dimension_key?: string | null;
            /** Metric Key */
            metric_key?: string | null;
            /** Unit */
            unit?: string | null;
            /** Data */
            data?: {
                [key: string]: string | number | null;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description 依赖服务暂时不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_demo_merchants_api_demo_merchants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoMerchantListResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description 默认返回 `text/event-stream`；请求头带 `Accept: application/json` 时返回普通 JSON。SSE 只发送 `step`、`done`、`error` 三种事件，流必须以 `done` 或 `error` 收尾。`step` 载荷是 `ThinkingStep`，`done` 载荷与 JSON 路径的 `ChatResponse` 逐字段相同，`error` 载荷是 `ErrorResponse`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                    /**
                     * @example event: step
                     *     data: {"label":"识别商家与业务意图","node":"classify"}
                     *
                     *     event: done
                     *     data: {"id":"...","session_id":"...","answer":"..."}
                     */
                    "text/event-stream": string;
                };
            };
            /** @description 缺少或提供了无效的商家凭证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 无权访问该资源或管理端点 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 幂等键冲突或同一请求正在处理中 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求参数不合法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 依赖服务暂时不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description 缺少或提供了无效的商家凭证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求参数不合法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description 缺少或提供了无效的商家凭证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 无权访问该资源或管理端点 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求参数不合法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 缺少或提供了无效的商家凭证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 无权访问该资源或管理端点 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求参数不合法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_export_api_exports__export_id__get: {
        parameters: {
            query: {
                merchant_id: string;
                expires_at: number;
                signature: string;
            };
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 无权访问该资源或管理端点 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 导出链接已过期 */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求参数不合法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_feedback_api_answers__answer_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description 缺少或提供了无效的商家凭证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 无权访问该资源或管理端点 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求参数不合法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_metric_definition_api_metrics__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricDefinitionResponse"];
                };
            };
            /** @description 缺少或提供了无效的商家凭证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 请求参数不合法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
