"""确定性中英词典：零 LLM 调用的固定词汇表。

只覆盖闭集、可枚举的固定词汇——状态码、指标/维度/明细列的展示名、单位、
业务域名称、质量循环的固定整句提示、限流与范围外拒答文案、演示数据的
闭集分类/原因/城市值。**不处理自由文本**（用户问题、模型生成的分析正文、
知识文档正文等）——那些走 `LocalizationService.localize_many()` 的 LLM
批量翻译路径，本模块完全不参与。

按来源文件分组，方便逐个核对来源文件的当前内容是否与本表一致；每个分组
前的注释标注真实来源路径。发现来源文件内容变化但本表没跟着更新，视为本
文件过期，需要重新核对后同步。

两处已核实的路径修正（相对任务描述里的原始文件清单）：

- 「问题分类的中文标签」实际定义在 `app/schemas/chat.py`
  的 `CATEGORY_DISPLAY_NAMES`，不在 `app/intent/models.py`——后者只有
  Pydantic 校验器和英文枚举，没有中文展示名常量；
- 「限流提示语」实际的用户可见文案在 `app/core/errors.py` 的
  `RateLimitedError`，`app/core/rate_limit.py` 本身只有滑动窗口算法，
  不含任何用户可见字符串。

`app/knowledge/domains.py` 的 `DOMAIN_KEYWORDS`/`ACTION_RULE_TERMS` 不在本表
范围内：它们是对**用户原始提问**做子串匹配用的关键词表，不是展示给用户的
输出文本——翻译它们只会让匹配失效，不会本地化任何界面内容。
"""

from __future__ import annotations

import re

from app.localization.locales import SupportedLocale

# ---------------------------------------------------------------------------
# 来源：backend/app/analytics/contract.py
# ---------------------------------------------------------------------------

#: METRIC_SPECS[*].label —— 指标展示名。
_CONTRACT_METRIC_LABELS: dict[str, str] = {
    "成交 GMV": "Transaction GMV",
    "订单量": "Order count",
    "下单用户数": "Ordering user count",
    "付款用户数": "Paying user count",
    "成功订单量": "Successful order count",
    "退款量": "Refund count",
    "退款金额": "Refund amount",
    "退货量": "Return count",
    "退货率": "Return rate",
    "客服工单量": "Support ticket count",
}

#: METRIC_SPECS[*].unit，与 visualization_service.py 单位表同一闭集。
_UNIT_LABELS: dict[str, str] = {
    "元": "yuan",
    "单": "orders",
    "人": "users",
    "件": "items",
    "%": "%",
}

#: DIMENSION_SPECS[*].label —— 查询维度展示名。
_CONTRACT_DIMENSION_LABELS: dict[str, str] = {
    "日期": "Date",
    "商品": "Product",
    "类目": "Category",
    "订单状态": "Order status",
    "退款原因": "Refund reason",
    "退货原因": "Return reason",
    "退货状态": "Return status",
    "工单状态": "Ticket status",
}

#: DETAIL_SPECS[*].label（明细表标题）与 DETAIL_SPECS[*].columns 里的列中文标签。
_CONTRACT_DETAIL_LABELS: dict[str, str] = {
    "订单明细": "Order details",
    "退款明细": "Refund details",
    "退货明细": "Return details",
    "商品明细": "Product details",
    "工单明细": "Ticket details",
    "订单号": "Order no.",
    "实付金额": "Paid amount",
    "下单时间": "Placed at",
    "退款时间": "Refunded at",
    "退货件数": "Return quantity",
    "物流状态": "Logistics status",
    "上架日": "Listed date",
    "商品编码": "Product code",
    "商品名称": "Product title",
    "价格": "Price",
    "状态": "Status",
    "工单号": "Ticket no.",
    "工单类型": "Ticket reason",
    "创建时间": "Created at",
    # 与 _CONTRACT_DIMENSION_LABELS/_CONTRACT_METRIC_LABELS 重复的列标签
    # （日期/订单状态/退款原因/退款金额/退款状态/退货原因/退货状态/类目）
    # 已在上面两张表登记，取值完全一致，此处不重复列出。
    "退款状态": "Refund status",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/metrics/field_comments.py
# ---------------------------------------------------------------------------

#: FIELD_COMMENT_DEFINITIONS[*].business_definition —— 字段人类可读注释整句。
#: sql_definition（如 "SUM(orders.paid_amount)"）本身是 SQL，不翻译。
_FIELD_COMMENT_DEFINITIONS: dict[str, str] = {
    "已支付订单的实付金额。": "The paid amount of completed orders.",
    "订单主键数量。": "Count of order primary keys.",
    "统计周期内创建订单的去重买家数，不要求完成付款。": (
        "The number of distinct buyers who placed orders during the period, "
        "regardless of whether payment was completed."
    ),
    "已付款订单中的去重买家数。": "The number of distinct buyers among paid orders.",
    "交易成功状态的订单数量。": "The number of orders in completed status.",
    "退款记录数量。": "Count of refund records.",
    "退款记录的退款金额。": "The refund amount of refund records.",
    "退货记录的商品件数。": "The item quantity of return records.",
    "退货件数与订单项件数的比率。": (
        "The ratio of returned item quantity to order item quantity."
    ),
    "客服工单记录数量。": "Count of support ticket records.",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/metrics/catalog.py
# ---------------------------------------------------------------------------

#: GENERATED_NOTICE —— 未命中正式目录/字段注释时，AI 生成口径附带的整段提示；
#: 以及生成/字段注释两条路径各自写入 MetricPayload.owner 的固定字面量。
_METRIC_CATALOG_MISC: dict[str, str] = {
    (
        "该指标口径未命中正式指标目录或字段注释，"
        "以下内容由大模型根据当前问题生成，仅供参考，请以正式指标口径为准。"
    ): (
        "This metric definition did not match the official metric catalog or "
        "field comments. The following content was generated by the model "
        "based on the current question, for reference only — defer to the "
        "official metric definition."
    ),
    "字段注释": "Field comment",
    "待认领": "Unclaimed",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/schemas/chat.py（CATEGORY_DISPLAY_NAMES）
# ---------------------------------------------------------------------------

_CATEGORY_DISPLAY_NAMES: dict[str, str] = {
    "平台商家规则": "Platform merchant rules",
    "电商交易": "E-commerce trade",
    "电商退货": "E-commerce returns",
    "电商客服工单": "E-commerce support tickets",
    "电商理赔/赔付": "E-commerce claims/compensation",
    "电商优惠券": "E-commerce coupons",
    "商品管理": "Product management",
    "商家其他信息": "Other merchant information",
    "身份信息": "Identity information",
    "供应链": "Supply chain",
    "未知": "Unknown",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/services/quality_loop.py
# ---------------------------------------------------------------------------

_QUALITY_LOOP_MESSAGES: dict[str, str] = {
    "今日模型用量已达上限，本次只提供受控数据摘要": (
        "Today's model usage quota has been reached; only a controlled data "
        "summary is provided this time."
    ),
    "模型返回空正文，请重新只输出完整 JSON": (
        "The model returned an empty response body; please output the "
        "complete JSON only."
    ),
    "上一版输出无法解析为约定的 JSON 对象，请只输出完整 JSON": (
        "The previous output could not be parsed as the agreed JSON object; "
        "please output the complete JSON only."
    ),
    "未执行独立复核，本次只提供受控数据摘要": (
        "Independent review was not performed; only a controlled data "
        "summary is provided this time."
    ),
    "达到最大重试次数，使用确定性降级结果": (
        "Maximum retry count reached; using the deterministic fallback "
        "result."
    ),
    "模型或独立复核暂不可用，本次只提供受控数据摘要": (
        "The model or independent review is temporarily unavailable; only a "
        "controlled data summary is provided this time."
    ),
    "本次请求的模型预算已达上限，本次只提供受控数据摘要": (
        "The model budget for this request has been reached; only a "
        "controlled data summary is provided this time."
    ),
    "回答未通过校验，本次只提供受控数据摘要": (
        "The answer failed validation; only a controlled data summary is "
        "provided this time."
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/core/errors.py（RateLimitedError 的用户可见文案）
# ---------------------------------------------------------------------------

_RATE_LIMIT_MESSAGES: dict[str, str] = {
    "请求过于频繁，请稍后重试": "Too many requests, please try again later.",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/agent/graph.py（_PREFILTER_REJECTION_MESSAGE）
# ---------------------------------------------------------------------------

_PREFILTER_REJECTION_MESSAGES: dict[str, str] = {
    (
        "我是 Borough 商家 AI 助手，只能回答与您店铺经营相关的问题，"
        "例如成交额、订单、退款、商品或平台规则。换个和经营相关的问法试试？"
    ): (
        "I'm the Borough Merchant AI Assistant, and I can only answer "
        "questions related to your store's operations, such as GMV, orders, "
        "refunds, products, or platform rules. Please try rephrasing your "
        "question to relate to your business."
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/services/answer_service.py（_ADDITIVE_CLAIM_PHRASES）
#
# Task 5：聚合断言校验（"非加和指标不能被合计"）过去只认中文关键词，英文回答
# 说 "totalled"/"combined" 之类的话完全绕过检查。中英文关键词都从这里统一取，
# 不再各写一套正则——`answer_service.py` 在导入时通过 `localize_catalog_value`
# 反查出英文形式，拼进同一份大小写不敏感的匹配列表。
# ---------------------------------------------------------------------------

#: 英文译文刻意避开裸词 "sum"——它是 "summary"/"consumer" 等常见词的前缀子串，
#: 用作子串匹配关键词会大量误伤；"summed" 覆盖模型最可能出现的措辞
#: （"the values summed to 18"），同时不与那些常见词冲突。
_ADDITIVE_CLAIM_TRANSLATIONS: dict[str, str] = {
    "合计": "total",
    "总计": "total",
    "累计": "cumulative",
    "总和": "summed",
    "加总": "combined",
    "汇总": "aggregate",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/services/review_service.py —— Reviewer 调用失败/输出异常
# 的固定提示语。Task 4 只登记了 quality_loop.py 的整句提示，漏了本文件。
# ---------------------------------------------------------------------------

_REVIEW_SERVICE_MESSAGES: dict[str, str] = {
    "Reviewer 暂不可用": "Independent review is currently unavailable.",
    "Reviewer 输出为空，请只输出完整 JSON": (
        "The reviewer output was empty; please output the complete JSON only."
    ),
    "Reviewer 输出无法解析为约定 JSON": (
        "The reviewer output could not be parsed as the agreed JSON."
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/agent/graph.py（_quality_degrade_reason）—— 写入
# `degraded_reason` 单值字段的整句说明；与 quality_loop.py 写入 `quality_notes`
# 列表的提示语是不同的两句话，即使指向同一个 DegradeReason，也要分别登记。
# ---------------------------------------------------------------------------

_GRAPH_DEGRADE_REASON_MESSAGES: dict[str, str] = {
    "回答生成或独立复核暂不可用，已返回受控数据摘要。": (
        "Answer generation or independent review is temporarily unavailable; "
        "a controlled data summary has been returned."
    ),
    "模型预算已达上限，已返回受控数据摘要。": (
        "The model budget has been reached; a controlled data summary has "
        "been returned."
    ),
    "回答未通过质量校验，已返回受控数据摘要。": (
        "The answer did not pass quality validation; a controlled data "
        "summary has been returned."
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/services/answer_service.py（AnswerService._validate()）——
# 本地校验产出的 issue 文案，最终经 quality_loop.py 的 `_REJECT_NOTE_TEMPLATES`
# 拼进 `quality_notes`。Task 6 补充登记（Task 5 交付语言无关校验逻辑时，
# 校验 issue 文案本身尚未接入 locale 渲染，属于 Task 6 的接线范围，见
# `_validate()` 的 `locale` 参数）。
#
# 「以下数字不在查询结果或事实摘要里，不得出现在回答中：」后面跟的是动态
# 拼接的数字列表，不是固定整句，这里只登记**前缀**——`_validate()` 里按
# locale 选取前缀后自行拼接数字列表，不通过本表做整句精确匹配。
# ---------------------------------------------------------------------------

_ANSWER_VALIDATION_MESSAGES: dict[str, str] = {
    "回答含有内部标识符，不得出现在对商家的回答里": (
        "The answer contains an internal identifier, which must not appear "
        "in a merchant-facing answer."
    ),
    "非加和指标不能被回答草稿合计或汇总": (
        "This non-additive metric must not be totalled or summed in the "
        "answer draft."
    ),
    "回答陈述的日期区间超出了本次查询的实际范围": (
        "The date range stated in the answer exceeds the actual range of "
        "this query."
    ),
    "以下数字不在查询结果或事实摘要里，不得出现在回答中：": (
        "The following numbers are not in the query result or fact summary "
        "and must not appear in the answer: "
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/knowledge/path_policy.py（BUSINESS_SECTIONS）与
# backend/app/services/knowledge_admin_service.py（虚拟目录树固定节点名，
# Task 8 Step 4 "树节点只本地化 name"）。这是闭集的固定导航标签,不是用户
# 创建的业务域名称或任意文档标题——那些不在本表范围内,原样保留。
# ---------------------------------------------------------------------------

_KNOWLEDGE_TREE_LABELS: dict[str, str] = {
    "业务": "Business",
    "业务流程": "Business process",
    "业务名词解释": "Business glossary",
    "指标或调用指标平台mcp的skill": "Metrics / metrics-platform MCP skill",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/repositories/analytics.py（ResultColumn 内联中文标签）
#
# Task 8：跨业务关联查询与临时分组指标导出用到的列标签是直接写在仓储代码里
# 的字面量，不经过 `analytics/contract.py` 的注册表；与已经登记在
# `_CONTRACT_*` 分组里的同名列（订单号/订单状态/实付金额/商品编码/商品名称/
# 退款金额/退款原因/退款状态/退款时间）取值一致，此处不重复登记，只补上
# 尚未出现过的新标签。"SPU ID" 本身不含汉字，不需要词典条目。
# ---------------------------------------------------------------------------

_ANALYTICS_REPOSITORY_LABELS: dict[str, str] = {
    "SPU 名称": "SPU name",
    "收货城市": "Shipping city",
    "成交订单数": "Completed order count",
    "成交用户数": "Completed order user count",
    "成交件数": "Completed item quantity",
    "成交金额": "Completed amount",
    "退款笔数": "Refund count",
    "退款用户数": "Refund user count",
    "商品类目": "Product category",
    "购买数量": "Purchased quantity",
    "商品金额": "Product amount",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/services/report_service.py —— 每日经营日报固定建议与
# 降级说明（Task 8）。`_suggestions()` 只从这 6 句固定组合里二选二，
# `_build_response()` 的降级分支只用这 1 句——是与 quality_loop.py 同类的
# 闭集固定整句，不属于需要模型翻译的自由文本。
# ---------------------------------------------------------------------------

_DAILY_REPORT_MESSAGES: dict[str, str] = {
    "暂无近 7 日经营数据，建议保持商品供给和客服响应稳定。": (
        "No operating data is available for the past 7 days yet. We recommend "
        "keeping product supply and customer service response steady."
    ),
    "可以先补齐商品、保证金和商家资料，提升平台经营基础。": (
        "Consider completing your product listings, deposit, and merchant "
        "profile first to strengthen your store's operating foundation."
    ),
    "近 7 日存在退款金额，建议优先查看退货退款明细，定位高频原因并优化发货/售后说明。": (
        "Refunds occurred in the past 7 days. We recommend reviewing the "
        "return/refund details first to identify frequent causes and improve "
        "shipping/after-sales information."
    ),
    "近 7 日退款压力较低，可以继续保持履约和售后响应稳定。": (
        "Refund pressure has been low over the past 7 days. Keep fulfillment "
        "and after-sales response steady."
    ),
    "客服工单相对订单量偏高，建议排查催单、物流和商品说明类问题。": (
        "Support tickets are relatively high compared to order volume. We "
        "recommend checking for order-urging, logistics, and "
        "product-description issues."
    ),
    "建议继续关注 GMV、交易成功订单量和优惠使用效果，挑选转化较好的商品加大运营。": (
        "Continue monitoring GMV, successful order volume, and coupon "
        "effectiveness, and scale up promotion for better-converting "
        "products."
    ),
    "经营数据暂时不可用，本期日报未生成指标。": (
        "Operating data is temporarily unavailable; no metrics were "
        "generated for this period's report."
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/metrics/seed.py（METRIC_SEED[*].business_definition）与
# owner 字面量 "经营分析组"（Task 8）。这批口径整句与
# `_FIELD_COMMENT_DEFINITIONS`（来源 `metrics/field_comments.py`）文字不同——
# 前者是正式指标目录的业务口径，后者是二级降级用的字段注释，两套整句都要
# 分别登记，不能只登记一套。
# ---------------------------------------------------------------------------

_METRIC_SEED_DEFINITIONS: dict[str, str] = {
    "统计周期内已支付订单金额之和。": "Sum of paid order amounts during the period.",
    "统计周期内创建的订单数量。": "Number of orders created during the period.",
    "统计周期内创建订单的去重用户数，不要求完成付款。": (
        "Number of distinct users who placed orders during the period, "
        "regardless of whether payment was completed."
    ),
    "统计周期内完成付款的去重用户数。": (
        "Number of distinct users who completed payment during the period."
    ),
    "统计周期内交易成功的订单数量。": (
        "Number of orders that completed successfully during the period."
    ),
    "统计周期内发起退款的订单数量。": (
        "Number of orders with refunds initiated during the period."
    ),
    "统计周期内退款总金额。": "Total refund amount during the period.",
    "统计周期内发起退货的商品件数。": (
        "Number of item units returned during the period."
    ),
    "退货件数除以同期订单项件数，按查询区间重新计算，不可跨日相加。": (
        "Returned item quantity divided by order item quantity for the same "
        "period; recalculated per query range and not additive across days."
    ),
    "统计周期内创建的客服工单数量。": (
        "Number of support tickets created during the period."
    ),
    "经营分析组": "Business Analytics Team",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/analytics/demo_data.py —— 闭集分类/原因/城市中文值
# ---------------------------------------------------------------------------

_DEMO_DATA_VALUES: dict[str, str] = {
    # _CATEGORIES
    "女装": "Women's wear",
    "男装": "Men's wear",
    "鞋靴": "Shoes",
    "家居": "Home goods",
    "美妆": "Beauty",
    # _REFUND_REASONS ∪ _RETURN_REASONS（"商品质量问题"/"尺码不合适" 两表共用）
    "商品质量问题": "Product quality issue",
    "尺码不合适": "Wrong size",
    "发货太慢": "Slow shipping",
    "拍错了": "Ordered by mistake",
    "不想要了": "No longer wanted",
    "与描述不符": "Not as described",
    "包装破损": "Damaged packaging",
    # _TICKET_REASONS
    "物流查询": "Logistics inquiry",
    "退款进度": "Refund progress",
    "商品咨询": "Product inquiry",
    "投诉建议": "Complaint/suggestion",
    # _CITIES
    "杭州市": "Hangzhou",
    "深圳市": "Shenzhen",
    "广州市": "Guangzhou",
    "成都市": "Chengdu",
    "武汉市": "Wuhan",
}

# ---------------------------------------------------------------------------
# 状态码美化：demo_data.py 的英文状态码闭集，以及 schemas/chat.py 的
# QualityStatus/AnalysisSource/MetricStatus/MetricDefinitionSource 枚举值。
#
# 这些码本身已经是英文契约码（不是中文常量），中文界面历来也是直接展示原始
# 码（代码库里不存在任何「PAID -> 已支付」式的中文标签映射可抄）——因此这里
# 只提供 en-US 的人类可读展示形式（"PAID" -> "Paid"），zh-CN 目标语言下保持
# 原码不变（`localize_catalog_value` 的通用规则：zh-CN 一律原样返回）。
# 编造一套中文状态标签属于产品决策，不属于「照抄现有常量」的词典抄录范围。
# ---------------------------------------------------------------------------

_STATUS_CODES: tuple[str, ...] = (
    # demo_data.py：_ORDER_STATUSES
    "CREATED",
    "PAID",
    "SHIPPED",
    "COMPLETED",
    "CANCELLED",
    "CLOSED",
    # demo_data.py：_refund_row() 内联的 refund_status 取值
    "REFUNDED",
    "PENDING",
    # demo_data.py：_RETURN_STATUSES
    "REQUESTED",
    "APPROVED",
    "RECEIVED",
    "REJECTED",
    # demo_data.py：_LOGISTICS_STATUSES
    "DELIVERED",
    "LOST",
    # demo_data.py：_TICKET_STATUSES
    "OPEN",
    "RESOLVED",
    # demo_data.py：build_demo_catalog() 内联的 product status 取值
    "ONLINE",
    "AUDITING",
    # schemas/chat.py：QualityStatus
    "PASSED",
    "DEGRADED",
    "FAILED",
    "NOT_RUN",
    # schemas/chat.py：AnalysisSource
    "DATABASE",
    "KNOWLEDGE",
    "ATTACHMENT",
    "MEMORY",
    "FALLBACK",
    "NONE",
    # schemas/chat.py：MetricStatus
    "ACTIVE",
    "DEPRECATED",
    "UNVERIFIED",
    # schemas/chat.py：MetricDefinitionSource
    "METRIC_CATALOG",
    "FIELD_COMMENT",
    "AI_GENERATED",
)

#: 少数缩写在美化时需要保持整体大写，不能被逐词首字母大写规则拆散。
_ACRONYM_OVERRIDES: dict[str, str] = {
    "AI": "AI",
}


def _beautify_status_code(code: str) -> str:
    """`"NOT_RUN"` -> `"Not Run"`；`"AI_GENERATED"` -> `"AI Generated"`。"""

    words = code.split("_")
    return " ".join(_ACRONYM_OVERRIDES.get(word, word.capitalize()) for word in words)


_STATUS_LABELS: dict[str, str] = {code: _beautify_status_code(code) for code in _STATUS_CODES}


def _merge_translations(*groups: dict[str, str]) -> dict[str, str]:
    """合并各来源分组；同一 key 出现在多组时必须给出完全相同的译文。

    真实出现的重复 key（如 "日期"/"类目"/"退款金额" 同时是维度标签和明细列
    标签）本身就该翻译成同一个词，这里的冲突检测只是防止后续编辑分组时
    不小心让同一个中文/码在两处译出两种不同的英文。
    """

    merged: dict[str, str] = {}
    for group in groups:
        for key, value in group.items():
            existing = merged.get(key)
            if existing is not None and existing != value:
                raise ValueError(
                    f"确定性词典冲突：{key!r} 同时被译为 {existing!r} 和 {value!r}"
                )
            merged[key] = value
    return merged


_TRANSLATIONS: dict[str, str] = _merge_translations(
    _CONTRACT_METRIC_LABELS,
    _UNIT_LABELS,
    _CONTRACT_DIMENSION_LABELS,
    _CONTRACT_DETAIL_LABELS,
    _FIELD_COMMENT_DEFINITIONS,
    _METRIC_CATALOG_MISC,
    _CATEGORY_DISPLAY_NAMES,
    _QUALITY_LOOP_MESSAGES,
    _RATE_LIMIT_MESSAGES,
    _PREFILTER_REJECTION_MESSAGES,
    _ADDITIVE_CLAIM_TRANSLATIONS,
    _REVIEW_SERVICE_MESSAGES,
    _GRAPH_DEGRADE_REASON_MESSAGES,
    _ANSWER_VALIDATION_MESSAGES,
    _KNOWLEDGE_TREE_LABELS,
    _ANALYTICS_REPOSITORY_LABELS,
    _DAILY_REPORT_MESSAGES,
    _METRIC_SEED_DEFINITIONS,
    _DEMO_DATA_VALUES,
    _STATUS_LABELS,
)


def localize_catalog_value(value: str, target_locale: SupportedLocale) -> str | None:
    """零 LLM 的确定性词典查找。

    - 未命中词典：返回 `None`，调用方据此判断需要走 LLM 批量翻译路径；
    - 命中且目标语言是 `zh-CN`：原样返回 `value`（词典的 key 本身就是当前
      展示形态，不需要也不应该改写）；
    - 命中且目标语言是 `en-US`：返回词典登记的英文译文。
    """

    if value not in _TRANSLATIONS:
        return None
    if target_locale is SupportedLocale.ZH_CN:
        return value
    return _TRANSLATIONS[value]


# ---------------------------------------------------------------------------
# Task 5：问题范围前置闸门（`app/agent/prefilter.py`）专用的双语数据表。
#
# 停用词表与上面的 `_TRANSLATIONS` 是两类不同的东西：`_TRANSLATIONS` 把固定
# 词汇翻译成另一种语言的**展示文本**；这里的停用词表和下面的业务词反查表都是
# 对**用户原始提问**做匹配用的关键词表，不产出任何展示给用户的文本——与文件
# 顶部说明里 `DOMAIN_KEYWORDS`/`ACTION_RULE_TERMS` 不进 `_TRANSLATIONS` 是同一
# 条边界。之所以仍放在本模块，是因为闸门需要的英文业务词表本身就是从
# `_TRANSLATIONS` 已登记的中文名词反查出来的，与翻译表同源、不宜拆到别处。
# ---------------------------------------------------------------------------

#: 现代汉语功能词封闭集合，从 `app/agent/prefilter.py` 迁移到此处集中维护。
ZH_STOPWORDS: frozenset[str] = frozenset(
    {
        "请问",
        "什么",
        "怎么",
        "为什么",
        "一下",
        "可以",
        "是否",
        "的话",
        "如何",
        "哪些",
        "哪个",
        "多少",
        "这个",
        "那个",
    }
)

#: 英文功能词封闭集合，与 `ZH_STOPWORDS` 并列。只收录不带业务含义、会在打分时
#: 制造噪音的通用词（疑问词、系动词、冠词、介词……）；刻意不收录 "and"/"or"
#: 这类可能出现在正当业务问法里的连词（如「CNN and RNN 的区别」式合并问法）。
EN_STOPWORDS: frozenset[str] = frozenset(
    {
        "what",
        "which",
        "who",
        "whom",
        "when",
        "where",
        "why",
        "how",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "the",
        "a",
        "an",
        "of",
        "to",
        "for",
        "in",
        "on",
        "at",
        "by",
        "with",
        "do",
        "does",
        "did",
        "please",
        "can",
        "could",
        "would",
        "will",
        "i",
        "you",
        "your",
        "my",
        "me",
        "we",
        "us",
        "our",
        "this",
        "that",
        "it",
    }
)

#: 参与闸门双语同义词反查的业务词表分组——只取指标/维度/明细列/问题分类的
#: 固定展示名，不取整句提示、状态码或演示数据：那些不是知识语料标题/路径里
#: 会出现的检索关键词，混进来只会制造无意义的反查命中。
_BUSINESS_TERM_GROUPS: tuple[dict[str, str], ...] = (
    _CONTRACT_METRIC_LABELS,
    _CONTRACT_DIMENSION_LABELS,
    _CONTRACT_DETAIL_LABELS,
    _CATEGORY_DISPLAY_NAMES,
)


def _build_business_terms_en_to_zh() -> dict[str, tuple[str, ...]]:
    index: dict[str, list[str]] = {}
    for group in _BUSINESS_TERM_GROUPS:
        for zh_term, en_label in group.items():
            for word in re.findall(r"[A-Za-z]+", en_label.lower()):
                bucket = index.setdefault(word, [])
                if zh_term not in bucket:
                    bucket.append(zh_term)
    return {word: tuple(zh_terms) for word, zh_terms in index.items()}


#: 英文单词（小写、已去除标点）-> 对应的中文业务词表 key 列表。例如
#: "refund" 命中 "退款金额"/"退款量"/"退款明细"/"退款原因"/"退款状态"。
_BUSINESS_TERMS_EN_TO_ZH: dict[str, tuple[str, ...]] = _build_business_terms_en_to_zh()


def zh_business_terms_for_english_word(word: str) -> tuple[str, ...]:
    """反查一个英文词命中的中文业务词表 key（指标/维度/明细列/分类展示名）。

    闸门打分语料（知识文档标题、正式指标目录、商家记忆）几乎全是中文，英文
    问题里的业务词直接拿去打分只会全部落空。这张表让英文词能"翻译"回中文
    候选词，再用**现成的、未经修改的**打分逻辑评分——不引入 LLM，也不修改
    语料本身，只是在提问侧补上等价的中文检索词（design.md 与 Task 5 brief
    Step 5 的"语料侧建立确定性双语词项映射"）。

    未命中返回空元组，调用方据此判断该英文词没有可反查的中文业务词——这不
    代表问题一定范围外，闸门仍会继续走既有的打分/`ALLOW_CORPUS_UNAVAILABLE`
    兜底路径。
    """

    return _BUSINESS_TERMS_EN_TO_ZH.get(word.lower(), ())


# ---------------------------------------------------------------------------
# Task 5：`app/services/visualization_service.py` 生成指标的数值列选择——
# 过去按 `metric.display_name` 里的中文子串（"金额"/"用户"/"销量"……）猜测，
# 模型说英文时这套子串匹配全部落空。改为只认 `metric.unit`，并通过下面的
# 单位登记表反查回统一的中文单位 key，使中英文推断结果必然一致；
# `display_name` 只负责渲染，不再参与推断。
# ---------------------------------------------------------------------------

_UNIT_EN_TO_ZH: dict[str, str] = {en.lower(): zh for zh, en in _UNIT_LABELS.items()}


def normalize_unit_to_zh(unit: str) -> str | None:
    """把任意语言书写的单位字符串归一化为 `_UNIT_LABELS` 登记的中文单位 key。

    命中中文 key 本身（如 "元"）或其登记的英文译文（如 "yuan"，大小写不敏感）
    都返回同一个中文 key；两者都未命中返回 `None`——调用方按未识别单位处理，
    不得凭空猜一个默认值。
    """

    candidate = unit.strip()
    if candidate in _UNIT_LABELS:
        return candidate
    return _UNIT_EN_TO_ZH.get(candidate.lower())
