"""确定性中英词典：零 LLM 调用的固定词汇表。

只覆盖闭集、可枚举的固定词汇——状态码、指标/维度/明细列的展示名、单位、
业务域名称、质量循环的固定整句提示、限流与范围外拒答文案、演示数据的
闭集分类/原因/城市值。**不处理自由文本**（用户问题、模型生成的分析正文、
知识文档正文等）——那些走 `LocalizationService.localize_many()` 的 LLM
批量翻译路径，本模块完全不参与。

按来源文件分组，方便逐个核对来源文件的当前内容是否与本表一致；每个分组
前的注释标注真实来源路径。发现来源文件内容变化但本表没跟着更新，视为本
文件过期，需要重新核对后同步。

两处已核实的路径修正（相对任务描述里的原始文件清单）：

- 「问题分类的中文标签」实际定义在 `app/schemas/chat.py`
  的 `CATEGORY_DISPLAY_NAMES`，不在 `app/intent/models.py`——后者只有
  Pydantic 校验器和英文枚举，没有中文展示名常量；
- 「限流提示语」实际的用户可见文案在 `app/core/errors.py` 的
  `RateLimitedError`，`app/core/rate_limit.py` 本身只有滑动窗口算法，
  不含任何用户可见字符串。

`app/knowledge/domains.py` 的 `DOMAIN_KEYWORDS`/`ACTION_RULE_TERMS` 不在本表
范围内：它们是对**用户原始提问**做子串匹配用的关键词表，不是展示给用户的
输出文本——翻译它们只会让匹配失效，不会本地化任何界面内容。
"""

from __future__ import annotations

from app.localization.locales import SupportedLocale

# ---------------------------------------------------------------------------
# 来源：backend/app/analytics/contract.py
# ---------------------------------------------------------------------------

#: METRIC_SPECS[*].label —— 指标展示名。
_CONTRACT_METRIC_LABELS: dict[str, str] = {
    "成交 GMV": "Transaction GMV",
    "订单量": "Order count",
    "下单用户数": "Ordering user count",
    "付款用户数": "Paying user count",
    "成功订单量": "Successful order count",
    "退款量": "Refund count",
    "退款金额": "Refund amount",
    "退货量": "Return count",
    "退货率": "Return rate",
    "客服工单量": "Support ticket count",
}

#: METRIC_SPECS[*].unit，与 visualization_service.py 单位表同一闭集。
_UNIT_LABELS: dict[str, str] = {
    "元": "yuan",
    "单": "orders",
    "人": "users",
    "件": "items",
    "%": "%",
}

#: DIMENSION_SPECS[*].label —— 查询维度展示名。
_CONTRACT_DIMENSION_LABELS: dict[str, str] = {
    "日期": "Date",
    "商品": "Product",
    "类目": "Category",
    "订单状态": "Order status",
    "退款原因": "Refund reason",
    "退货原因": "Return reason",
    "退货状态": "Return status",
    "工单状态": "Ticket status",
}

#: DETAIL_SPECS[*].label（明细表标题）与 DETAIL_SPECS[*].columns 里的列中文标签。
_CONTRACT_DETAIL_LABELS: dict[str, str] = {
    "订单明细": "Order details",
    "退款明细": "Refund details",
    "退货明细": "Return details",
    "商品明细": "Product details",
    "工单明细": "Ticket details",
    "订单号": "Order no.",
    "实付金额": "Paid amount",
    "下单时间": "Placed at",
    "退款时间": "Refunded at",
    "退货件数": "Return quantity",
    "物流状态": "Logistics status",
    "上架日": "Listed date",
    "商品编码": "Product code",
    "商品名称": "Product title",
    "价格": "Price",
    "状态": "Status",
    "工单号": "Ticket no.",
    "工单类型": "Ticket reason",
    "创建时间": "Created at",
    # 与 _CONTRACT_DIMENSION_LABELS/_CONTRACT_METRIC_LABELS 重复的列标签
    # （日期/订单状态/退款原因/退款金额/退款状态/退货原因/退货状态/类目）
    # 已在上面两张表登记，取值完全一致，此处不重复列出。
    "退款状态": "Refund status",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/metrics/field_comments.py
# ---------------------------------------------------------------------------

#: FIELD_COMMENT_DEFINITIONS[*].business_definition —— 字段人类可读注释整句。
#: sql_definition（如 "SUM(orders.paid_amount)"）本身是 SQL，不翻译。
_FIELD_COMMENT_DEFINITIONS: dict[str, str] = {
    "已支付订单的实付金额。": "The paid amount of completed orders.",
    "订单主键数量。": "Count of order primary keys.",
    "统计周期内创建订单的去重买家数，不要求完成付款。": (
        "The number of distinct buyers who placed orders during the period, "
        "regardless of whether payment was completed."
    ),
    "已付款订单中的去重买家数。": "The number of distinct buyers among paid orders.",
    "交易成功状态的订单数量。": "The number of orders in completed status.",
    "退款记录数量。": "Count of refund records.",
    "退款记录的退款金额。": "The refund amount of refund records.",
    "退货记录的商品件数。": "The item quantity of return records.",
    "退货件数与订单项件数的比率。": (
        "The ratio of returned item quantity to order item quantity."
    ),
    "客服工单记录数量。": "Count of support ticket records.",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/metrics/catalog.py
# ---------------------------------------------------------------------------

#: GENERATED_NOTICE —— 未命中正式目录/字段注释时，AI 生成口径附带的整段提示；
#: 以及生成/字段注释两条路径各自写入 MetricPayload.owner 的固定字面量。
_METRIC_CATALOG_MISC: dict[str, str] = {
    (
        "该指标口径未命中正式指标目录或字段注释，"
        "以下内容由大模型根据当前问题生成，仅供参考，请以正式指标口径为准。"
    ): (
        "This metric definition did not match the official metric catalog or "
        "field comments. The following content was generated by the model "
        "based on the current question, for reference only — defer to the "
        "official metric definition."
    ),
    "字段注释": "Field comment",
    "待认领": "Unclaimed",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/schemas/chat.py（CATEGORY_DISPLAY_NAMES）
# ---------------------------------------------------------------------------

_CATEGORY_DISPLAY_NAMES: dict[str, str] = {
    "平台商家规则": "Platform merchant rules",
    "电商交易": "E-commerce trade",
    "电商退货": "E-commerce returns",
    "电商客服工单": "E-commerce support tickets",
    "电商理赔/赔付": "E-commerce claims/compensation",
    "电商优惠券": "E-commerce coupons",
    "商品管理": "Product management",
    "商家其他信息": "Other merchant information",
    "身份信息": "Identity information",
    "供应链": "Supply chain",
    "未知": "Unknown",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/services/quality_loop.py
# ---------------------------------------------------------------------------

_QUALITY_LOOP_MESSAGES: dict[str, str] = {
    "今日模型用量已达上限，本次只提供受控数据摘要": (
        "Today's model usage quota has been reached; only a controlled data "
        "summary is provided this time."
    ),
    "模型返回空正文，请重新只输出完整 JSON": (
        "The model returned an empty response body; please output the "
        "complete JSON only."
    ),
    "上一版输出无法解析为约定的 JSON 对象，请只输出完整 JSON": (
        "The previous output could not be parsed as the agreed JSON object; "
        "please output the complete JSON only."
    ),
    "未执行独立复核，本次只提供受控数据摘要": (
        "Independent review was not performed; only a controlled data "
        "summary is provided this time."
    ),
    "达到最大重试次数，使用确定性降级结果": (
        "Maximum retry count reached; using the deterministic fallback "
        "result."
    ),
    "模型或独立复核暂不可用，本次只提供受控数据摘要": (
        "The model or independent review is temporarily unavailable; only a "
        "controlled data summary is provided this time."
    ),
    "本次请求的模型预算已达上限，本次只提供受控数据摘要": (
        "The model budget for this request has been reached; only a "
        "controlled data summary is provided this time."
    ),
    "回答未通过校验，本次只提供受控数据摘要": (
        "The answer failed validation; only a controlled data summary is "
        "provided this time."
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/core/errors.py（RateLimitedError 的用户可见文案）
# ---------------------------------------------------------------------------

_RATE_LIMIT_MESSAGES: dict[str, str] = {
    "请求过于频繁，请稍后重试": "Too many requests, please try again later.",
}

# ---------------------------------------------------------------------------
# 来源：backend/app/agent/graph.py（_PREFILTER_REJECTION_MESSAGE）
# ---------------------------------------------------------------------------

_PREFILTER_REJECTION_MESSAGES: dict[str, str] = {
    (
        "我是 Borough 商家 AI 助手，只能回答与您店铺经营相关的问题，"
        "例如成交额、订单、退款、商品或平台规则。换个和经营相关的问法试试？"
    ): (
        "I'm the Borough Merchant AI Assistant, and I can only answer "
        "questions related to your store's operations, such as GMV, orders, "
        "refunds, products, or platform rules. Please try rephrasing your "
        "question to relate to your business."
    ),
}

# ---------------------------------------------------------------------------
# 来源：backend/app/analytics/demo_data.py —— 闭集分类/原因/城市中文值
# ---------------------------------------------------------------------------

_DEMO_DATA_VALUES: dict[str, str] = {
    # _CATEGORIES
    "女装": "Women's wear",
    "男装": "Men's wear",
    "鞋靴": "Shoes",
    "家居": "Home goods",
    "美妆": "Beauty",
    # _REFUND_REASONS ∪ _RETURN_REASONS（"商品质量问题"/"尺码不合适" 两表共用）
    "商品质量问题": "Product quality issue",
    "尺码不合适": "Wrong size",
    "发货太慢": "Slow shipping",
    "拍错了": "Ordered by mistake",
    "不想要了": "No longer wanted",
    "与描述不符": "Not as described",
    "包装破损": "Damaged packaging",
    # _TICKET_REASONS
    "物流查询": "Logistics inquiry",
    "退款进度": "Refund progress",
    "商品咨询": "Product inquiry",
    "投诉建议": "Complaint/suggestion",
    # _CITIES
    "杭州市": "Hangzhou",
    "深圳市": "Shenzhen",
    "广州市": "Guangzhou",
    "成都市": "Chengdu",
    "武汉市": "Wuhan",
}

# ---------------------------------------------------------------------------
# 状态码美化：demo_data.py 的英文状态码闭集，以及 schemas/chat.py 的
# QualityStatus/AnalysisSource/MetricStatus/MetricDefinitionSource 枚举值。
#
# 这些码本身已经是英文契约码（不是中文常量），中文界面历来也是直接展示原始
# 码（代码库里不存在任何「PAID -> 已支付」式的中文标签映射可抄）——因此这里
# 只提供 en-US 的人类可读展示形式（"PAID" -> "Paid"），zh-CN 目标语言下保持
# 原码不变（`localize_catalog_value` 的通用规则：zh-CN 一律原样返回）。
# 编造一套中文状态标签属于产品决策，不属于「照抄现有常量」的词典抄录范围。
# ---------------------------------------------------------------------------

_STATUS_CODES: tuple[str, ...] = (
    # demo_data.py：_ORDER_STATUSES
    "CREATED",
    "PAID",
    "SHIPPED",
    "COMPLETED",
    "CANCELLED",
    "CLOSED",
    # demo_data.py：_refund_row() 内联的 refund_status 取值
    "REFUNDED",
    "PENDING",
    # demo_data.py：_RETURN_STATUSES
    "REQUESTED",
    "APPROVED",
    "RECEIVED",
    "REJECTED",
    # demo_data.py：_LOGISTICS_STATUSES
    "DELIVERED",
    "LOST",
    # demo_data.py：_TICKET_STATUSES
    "OPEN",
    "RESOLVED",
    # demo_data.py：build_demo_catalog() 内联的 product status 取值
    "ONLINE",
    "AUDITING",
    # schemas/chat.py：QualityStatus
    "PASSED",
    "DEGRADED",
    "FAILED",
    "NOT_RUN",
    # schemas/chat.py：AnalysisSource
    "DATABASE",
    "KNOWLEDGE",
    "ATTACHMENT",
    "MEMORY",
    "FALLBACK",
    "NONE",
    # schemas/chat.py：MetricStatus
    "ACTIVE",
    "DEPRECATED",
    "UNVERIFIED",
    # schemas/chat.py：MetricDefinitionSource
    "METRIC_CATALOG",
    "FIELD_COMMENT",
    "AI_GENERATED",
)

#: 少数缩写在美化时需要保持整体大写，不能被逐词首字母大写规则拆散。
_ACRONYM_OVERRIDES: dict[str, str] = {
    "AI": "AI",
}


def _beautify_status_code(code: str) -> str:
    """`"NOT_RUN"` -> `"Not Run"`；`"AI_GENERATED"` -> `"AI Generated"`。"""

    words = code.split("_")
    return " ".join(_ACRONYM_OVERRIDES.get(word, word.capitalize()) for word in words)


_STATUS_LABELS: dict[str, str] = {code: _beautify_status_code(code) for code in _STATUS_CODES}


def _merge_translations(*groups: dict[str, str]) -> dict[str, str]:
    """合并各来源分组；同一 key 出现在多组时必须给出完全相同的译文。

    真实出现的重复 key（如 "日期"/"类目"/"退款金额" 同时是维度标签和明细列
    标签）本身就该翻译成同一个词，这里的冲突检测只是防止后续编辑分组时
    不小心让同一个中文/码在两处译出两种不同的英文。
    """

    merged: dict[str, str] = {}
    for group in groups:
        for key, value in group.items():
            existing = merged.get(key)
            if existing is not None and existing != value:
                raise ValueError(
                    f"确定性词典冲突：{key!r} 同时被译为 {existing!r} 和 {value!r}"
                )
            merged[key] = value
    return merged


_TRANSLATIONS: dict[str, str] = _merge_translations(
    _CONTRACT_METRIC_LABELS,
    _UNIT_LABELS,
    _CONTRACT_DIMENSION_LABELS,
    _CONTRACT_DETAIL_LABELS,
    _FIELD_COMMENT_DEFINITIONS,
    _METRIC_CATALOG_MISC,
    _CATEGORY_DISPLAY_NAMES,
    _QUALITY_LOOP_MESSAGES,
    _RATE_LIMIT_MESSAGES,
    _PREFILTER_REJECTION_MESSAGES,
    _DEMO_DATA_VALUES,
    _STATUS_LABELS,
)


def localize_catalog_value(value: str, target_locale: SupportedLocale) -> str | None:
    """零 LLM 的确定性词典查找。

    - 未命中词典：返回 `None`，调用方据此判断需要走 LLM 批量翻译路径；
    - 命中且目标语言是 `zh-CN`：原样返回 `value`（词典的 key 本身就是当前
      展示形态，不需要也不应该改写）；
    - 命中且目标语言是 `en-US`：返回词典登记的英文译文。
    """

    if value not in _TRANSLATIONS:
        return None
    if target_locale is SupportedLocale.ZH_CN:
        return value
    return _TRANSLATIONS[value]
